### ISSUE TITLE
Need example

### ISSUE THREAD

**Issue by muturgan** [metarhia/metacom#189]
Please add a minimal server example just like in the jstp repo

**Comment by tshemsedinov** [comment]
Unlike `jstp` you can't simply create `metacom` server without `impress`, so use this example: https://github.com/metarhia/Example

**Comment by muturgan** [comment]
i'll try to explain my pain clearly.

well this is an example from the metacom readme:
``` js
const metacom = new Metacom('https://domainname.com:8000');
(async () => {
  try {
    await metacom.load('auth'); // Load `auth` interface
    await api.auth.status(); // Check session status
  } catch (err) {
    await api.auth.signIn({ login: 'marcus', password: 'marcus' });
  }
  await metacom.load('example'); // Load `example` interface
  const result = api.example.methodName({ arg1, arg2 });
})();
```
it looks like client code for me.

ok, but how i should understand that the server share "auth" and "example" interfaces and i can load it?
