### ISSUE TITLE
Metacom in React Native

### ISSUE THREAD

**Issue by sarnakov** [metarhia/metacom#204]
When I try  to use the library in RN I got an error "undefined is not a function" because there is no "window" object. To track the online status we use NetInfo.

I do not have a solution, but at least adding the listener may be wrapped by if or try/catch block.
What do you think?

Link to code line:
https://github.com/metarhia/metacom/blob/2d37779ffdaf45b93eda8fe66f7cbdcfd6830026/dist/metacom.js#L9

**Comment by tshemsedinov** [comment]
You can implement it with NetInfo and add it with `if (window)` or polyfill web api online notifications.

**Comment by sarnakov** [comment]
You are absolutely right, polyfill web api online seems perfect to me.
Thanks!
