### ISSUE TITLE
Add custom 404 pages

### ISSUE THREAD

**Issue by MarhiievHE** [metarhia/metacom#260]
It would be a nice feature to add support for custom 404 pages.

**Comment by georgolden** [comment]
Can you describe, what do you mean?

**Comment by MarhiievHE** [comment]
![image](https://user-images.githubusercontent.com/12165613/141864151-74e83229-1a63-4edc-833e-41f7a5e4377f.png)

**Comment by georgolden** [comment]
Ah ok. Thanks for clarification.

**Comment by tshemsedinov** [comment]
Done in 3.0.6
