### ISSUE TITLE
channels.get(...).redirect is not a function (channel.js)

### ISSUE THREAD

**Issue by alik-datsko** [metarhia/metacom#273]
It seems like the class WsChannel is missing a method redirect().
So in the class Client (channel.js) an error occurs in redirect

**Comment by georgolden** [comment]
Websocket is a tiny protocol for messaging. There is no `redirect` and must be no `redirect` in WebsocketChannel. HttpChannel has `redirect`. https://github.com/metarhia/metacom/blob/f7275df3c2a0ed56736004e2b1b659264a240463/lib/http.js#L53

**Comment by alik-datsko** [comment]
I lost sight of. Sorry. With the GET it works
