### ISSUE TITLE
Metacom ignores response when args is null or false

### ISSUE THREAD

**Issue by sarnakov** [metarhia/metacom#299]
When a client sends a request and receives a response from the server null or false, It ignores the response and throws an error "Request timeout" because of the condition "if (callId && args) {".

https://github.com/metarhia/metacom/blob/beef98ca06c296a191f163b9c596669d0f8177f1/dist/metacom.js#L65-L77

I`m not quite sure is it a bug, if not, I believe we need to throw another error, for example, "Unexpected response: null";

**Comment by tshemsedinov** [comment]
Thanks @sarnakov ! Fixed
