### ISSUE TITLE
Cover metacom streams with tests

### ISSUE THREAD

**Issue by rohiievych** [metarhia/metacom#327]
## How to implement
1. Create unit tests for streams functionality.
2. Create integration tests for complex use with Impress (see https://github.com/rohiievych/metacom-streams-example).

Create a PR to branch [streams](https://github.com/metarhia/metacom/tree/streams)

**Comment by pgnedoy** [comment]
@rohiievych 
1. Regarding unit tests everything is clear.
2. Do we have an example of the integration tests with impress? Just would like to look at how complex integration tests can be.

Is It okay to create two separate PRs. One for the unit tests, second for integration? Or better to proceed with a common one?

**Comment by rohiievych** [comment]
> @rohiievych
> 
> 1. Regarding unit tests everything is clear.
> 2. Do we have an example of the integration tests with impress? Just would like to look at how complex integration tests can be.
> 
> Is It okay to create two separate PRs. One for the unit tests, second for integration? Or better to proceed with a common one?

@pgnedoy Currently you can proceed with unit tests only.

Probably, it's better to create a separate repo for integration tests between different components of the tech stack.
@tshemsedinov What do you think about that?

**Comment by pgnedoy** [comment]
#333

**Comment by rohiievych** [comment]
Integration tests need further discussion
