### ISSUE TITLE
Browser version of events makes self invokes (recursion)

### ISSUE THREAD

**Issue by MidoMiddle** [metarhia/metacom#367]
## Describe the bug

Self invoked events (recursion)

## To Reproduce

I get files in dist: streams, metacom, events
Put it in Example (https://github.com/metarhia/Example), application/static
In the folder application/api/example create file: some.js

```javascript
({
  access: 'public',
  method: async () => {
    setTimeout(() => {
      context.client.emit('example/emit', 'from server');
    }, 1000 * 5);
    return 'success';
  },
});
```

Then in console, I invoke the endpoint: 
```javascript
await api.example.some()
```

After this front side gets event: -1 
And after making new api call: event: 1

## Expected behavior

I expected not to have emit from the front after the server answer

**Comment by tshemsedinov** [comment]
That is exactly how it should work. You call rpc method `const res = await api.example.some();` and receive answer `res === 'success'`; After that you wait for 5 sec and emit event `example/emit` from server to client. All calls have incremental ids: 1, 2, 3, etc. while all events have decremental ids: -1, -2, -3, etc.
