### ISSUE TITLE
Reorganize network connectivity tracking

### ISSUE THREAD

**Issue by URVL** [metarhia/metacom#468]
https://github.com/metarhia/metacom/blob/73272f9d1177079c70723e1ffc74c191b4114d4f/dist/metacom.js#L10

This piece of code is tied to the browser, and in this version, it cannot be used for example with react-native.
The variant used in react-native https://github.com/react-native-netinfo/react-native-netinfo

<img width="487" alt="Снимок экрана 2023-10-27 в 12 08 27" src="https://github.com/metarhia/metacom/assets/51157377/3ce29194-dc4d-4fc9-9bb0-2c0d402038ba">

**Comment by tshemsedinov** [comment]
We have no resources to support another one implementation for reat-native as of now

**Comment by tshemsedinov** [comment]
You can propose pull request
