### ISSUE TITLE
Stream does not end

### ISSUE THREAD

**Issue by mysilkworld** [metarhia/metacom#494]
## Describe the bug

During file transfer, the stream never ends due to an error in the library.

Arguments are passed incorrectly to the constructor [on line 299](https://github.com/metarhia/metacom/blob/47d3b350edfa2ea063617ce4cbaf5af36a5477b4/lib/server.js#L299)

Passed:
```js
const stream = new MetaReadable({ id, name, size });
```
Expected:
```js
class MetaReadable extends EventEmitter {
  constructor(id, name, size, options = {})
```

## To Reproduce

```js
({
  access: 'public',

  method: async ({ streamId }) => {
    const readable = context.client.getStream(streamId);

    const getChunks = async () => {
      console.log('start');
      const chunks = [];
      for await (const chunk of readable) {
        chunks.push(chunk);
      }
      console.log('end');
    };

    getChunks();

    return { result: 'Stream initialized' };
  },
});
```

## Expected behavior

The stream should end.

## Screenshots

No response

## Desktop (please complete the following information):

- OS: Windows 10
- Node.js version 20.11.1

## Additional context

No response

**Comment by tshemsedinov** [comment]
Please try to use streams
